version: 0.2

phases:
  pre_build:
    commands:
      
      - cd complete
      - chmod +x gradlew
  build:
    commands:
      - ./gradlew bootRepackage
  post_build:
    commands:
      - echo Build completed on `date`
      - mv build/libs/*.jar build/libs/application.jar
artifacts:
  files:
      - '*.jar'
  base-directory: complete/build/libs
      
